/* eslint-disable */
export const DEFAULT_TODOS = [
  {
    title: 'My Day',
    category: 'mytodo',
    active: true,
    todoListId: 0,
    iconSource: 'far fa-sun',
    sortOrder: '',
    currentDate: Date.now(),
    bgImage: './assets/retro.jpg',
    bgColor: 'blue',
  },
  {
    title: 'Important',
    category: 'important',
    active: false,
    todoListId: 1,
    iconSource: 'far fa-star',
    sortOrder: '',
    currentDate: 1532863416253,
    bgImage: './assets/retro.jpg',
    bgColor: 'blue',
  },
  {
    title: 'Tasks',
    category: 'todo',
    active: false,
    todoListId: 2,
    iconSource: 'fas fa-home',
    sortOrder: '',
    currentDate: 1531572460943,
    bgImage: './assets/retro.jpg',
    bgColor: 'blue',
  },
];
